bookings/urls.py
from django.urls import path
from . import views


app_name = "booking"

urlpatterns = [
    path("", views.BookingsListView.as_view(), name="listBookings"),
    path("book/<str:slug>/", views.book_service, name="bookService"),
    path("cancel/<int:id>/", views.cancel_booking, name="cancelService")
]

bookon/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

from users.views import Home
from users.views import home_page

urlpatterns = [
    path('home/', Home.as_view(), name="home_page2"),
    path('', home_page, name="home_page"),
    path('admin/', admin.site.urls),

    path('user/', include('users.urls', namespace="user")),

    path('services/', include('services.urls', namespace="services")),
    path('bookings/', include('bookings.urls', namespace="bookings")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

services/urls.py
from django.urls import path, re_path
from . import views

app_name = "services"

urlpatterns = [
    re_path(r'^$', views.ServiceListingView.as_view(), name="listServices"),
    path("<slug>/", views.ServiceDetail.as_view(), name="detailService"),
    path("register/service/", views.serviceRegistration,
         name="serviceRegistration"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "user"
urlpatterns = [

    path('signup/', views.customerSignupPage, name="customerSignupPage"),
    path('ownersignup/', views.ownerSignupPage, name="ownerSignupPage"),
    path('signin/', views.customerSigninPage, name="customerSigninPage"),
    path('signout/', views.signoutPage, name="signoutPage"),
    # dashboard
    path('dashboard/', views.owner_dashboard, name="owner_dashboard"),


]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous" />
  <link rel="stylesheet" href={% static 'bootstrap-4.4.1/css/bootstrap.min.css' %}>
  <link rel="stylesheet" href={% static 'css/main.css' %} />
  <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
    />
  <title>BookOn</title>
</head>

<body>

  {% comment %} <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href={% url 'home_page' %}>BookOn</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
      aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="my-2 my-lg-0 navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href={% url 'home_page' %}>Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href={% url 'booking:listBookings' %}>My Bookings</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href={% url 'services:listServices' %}>All services</a>
        </li>
        <li class="nav-link">
            Welcome, {{ user.first_name }}. <a href={% url 'user:signoutPage' %}> log out ?</a>
        </li>
          {% else %}
        <li>  Welcome, Please <a href={% url 'user:customerSigninPage' %}> log in </a> or <a href={% url 'user:customerSignupPage' %}>
            Create new account </a></li>
        <li>
          <a href={% url 'user:ownerSignupPage' %}> Sign up as owner</a>
        </li>
      {% endif %}
      </ul>
    </div>
  </nav> {% endcomment %}
<header>
      <nav class="header__container">
        <div class="header__logo">
          <a href={% url 'home_page' %} class="nav-link active">
            BookOn
          </a>
        </div>
        <div class="header__menu">
          <ul class="nav-links">
          {% if user.is_authenticated %}
            
              <!-- <li>
               <a class="nav-link" href={% url 'booking:listBookings' %}>My Bookings</a>
              </li>  -->
         
            {% if user.type == "OWNER" %}  
              <li>
                <a class="nav-link" href={% url 'user:owner_dashboard' %}>Dashboard</a>
              </li>
               <li>
                <a class="nav-link" href={% url 'services:serviceRegistration' %}>Add service </a>
              </li>
            {% endif %}  
              <li>
                <a class="nav-link" href={% url 'services:listServices' %}>All services</a>
              </li>
              <li>
                <a href={% url 'user:signoutPage' %} class="nav-link" > Log out ?</a>
              </li> 
            {% else %}
              <li><a href={% url 'user:customerSigninPage' %} class="nav-link" >Log in</a> </li> 
              <li><a href={% url 'user:customerSignupPage' %} class="n av-link">Signup</a></li> </li> 
              <li><a href={% url 'user:ownerSignupPage' %} class="nav-link btn-rounded btn-link">Sign up as Owner </a></li> </li> 
            {% endif %}
          </ul>
          <button
            class="icon-button menu-button"
            id="menu-button"
            {% comment %} onClick={(event) => {
              toggleMobileNavigation();
            }} {% endcomment %}
          >
            <div class="icon">
              <i class="material-icons" id="menu-icon">
                menu
              </i>
            </div>
          </button>
        </div>
      </nav>
      <div class="mobile-menu" id="mobile-menu">
        <ul class="mobile-nav-links" id="mobile-nav-links">
          <li>
            <a href={% url 'home_page' %} class="nav-link active">
              Home
            </a>
          </li>
          <li>
            <a href="" class="nav-link">
              Instagram
            </a>
          </li>
          <li>
            <a href="" class="nav-link">
              Twitter
            </a>
          </li>
          <li>
            <a href="" class="nav-link">
              Github
            </a>
          </li>
        </ul>
      </div>
    </header>
  {% block pageTitle %} {% endblock pageTitle %} {% if messages %}
  <ul class="messages mx-4 my-2" style="list-style:none;">
    {% for message in messages %}
  
 
        {% if message.tags %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show col-md-5" role="alert">
         {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
        </div>
        {% endif %}

  
      {% endfor %}
  </ul>
  {% endif %} 
  {% block content %} 
  {% endblock content %}
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
  </script>
  <script src={% static 'bootstrap-4.4.1/js/bootstrap.min.js.map' %}></script>
</body>

</html>

templates/home.html
{% extends "base.html" %} 



{% block content %}
    <section>
        <div class="section__container">
            <div class="section__left">
                <h2>Today's bookings</h2>
            </div>
            
            {% now "jS M, Y" %}
            <div class="section__right">
            {% if todays_booking %} 
                {% for booking in todays_booking %} 
                <div class="search-card">
                    <h3 class="search-card-title">{{ booking.service_name.title }}</h3>
                    <p class="search-card-subtitle">
                    ₹ {{booking.service_name.price}} / (
                    {{booking.service_name.average_service_time}} )
                    </p>
                    <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        {% if booking.start_time %} Time : {{booking.start_time}} {% else %}
                        Your service isn't being viewed / scheduled yet {% endif %}
                    </li>
                    <li class="list-group-item">
                        Address : {{booking.service_name.address}}
                    </li>
                    <li class="list-group-item">
                        <a
                        href="/bookings/cancel/{{booking.id}}/"
                        class="btn btn-danger content"
                        >Cancel</a
                        >
                        <a
                        href="/services/{{booking.service_name.slug}}/"
                        class="btn btn-info content float-right"
                        >Details</a
                        >
                    </li>
                    </ul>
                </div>
                {% endfor %} 
            {% else %}
                <p class="help-text">
                    Your schedule is clear today.
                </p>
            {% endif %}
            </div>
        </div>
    </section>
    <section>
        <div class="section__container">
            <div class="section__left">
            <h2>All bookings</h2>
            </div>
            <div class="section__right">
            {% if object_list %} {% for booking in object_list %}
            <div class="search-card">
                <h3 class="search-card-title">{{ booking.service_name.title }}</h3>
                <p class="search-card-subtitle">
                ₹ {{booking.service_name.price}} / (
                {{booking.service_name.average_service_time}} )
                </p>
                <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    {% if booking.start_time %}
                    Time : {{booking.start_time|date:"jS M, Y H:i A"}} 
                    {% else %} 
                    Your service isn't being viewed / scheduled by owner yet
                    {% endif %}
                
                </li>
                <li class="list-group-item">
                    Address : {{booking.service_name.address}}
                </li>
                <li class="list-group-item">
                    <a
                    href="/bookings/cancel/{{booking.id}}/"
                    class="btn btn-danger content"
                    >Cancel</a
                    >
                    <a
                    href="/services/{{booking.service_name.slug}}/"
                    class="btn btn-info content float-right"
                    >Details</a
                    >
                </li>
                </ul>
            </div>
            {% endfor %} {% else %}
            <h2>Nothing here, Book service from all services</h2>
            {% endif %}
            </div>
        </div>
    </section>
{% endblock content %}